### ISSUE TITLE
Response time is too high

### ISSUE THREAD

**Issue by rsoorajs** [ar-ekt/Google-Translator-Bot#1]
when i sent a text for converting it took apmost 5-10 seconds,for the translation.
tried several time changed server and everything..but still the problem is there..can you fix this and make it faster responsive ?

**Comment by ar-ekt** [comment]
I changed translator library. try it again

**Comment by rsoorajs** [comment]
okay..can you add the group translation feature too,which i mentioned.after that i will close this issue.

Thanks in advance

**Comment by rsoorajs** [comment]
> I changed translator library. try it again

Bot doesnt recognises  spaces,i mentioned that issue on telegram.please fix that too
